import { NextRequest, NextResponse } from 'next/server';
import { transporter, MAIL_FROM, MAIL_TO } from '@/lib/mailer';
import path from 'path';

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { name, mobile, email, company_name, message, product_id } = body;


    /* ── Validation ── */
    if (!name || !mobile || !email || !message) {
      return NextResponse.json(
        { error: 'Missing required fields: name, mobile, email, and message are required.' },
        { status: 400 }
      );
    }

    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
    if (!emailRegex.test(email)) {
      return NextResponse.json({ error: 'Invalid email format.' }, { status: 400 });
    }

    const mobileClean = mobile.replace(/[\s\-\+]/g, '');
    if (!/^\d{10,15}$/.test(mobileClean)) {
      return NextResponse.json({ error: 'Invalid mobile number format.' }, { status: 400 });
    }

    const receivedAt = new Date().toLocaleString('en-IN', {
      timeZone: 'Asia/Kolkata',
      dateStyle: 'full',
      timeStyle: 'short',
    });

    /* ── Email to owner ── */
    const htmlBody = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <style>
    body { font-family: Arial, sans-serif; background: #f4f6f9; margin: 0; padding: 0; }
    .wrapper { max-width: 600px; margin: 30px auto; background: #fff; border-radius: 12px; overflow: hidden; box-shadow: 0 4px 20px rgba(0,0,0,0.08); }
    .header { background: linear-gradient(135deg, #001a3a, #003580); padding: 28px 32px; }
    .header h1 { color: #00b4d8; margin: 0 0 4px; font-size: 22px; }
    .header p { color: #90caf9; margin: 0; font-size: 13px; }
    .badge { display: inline-block; background: #00b4d8; color: #fff; font-size: 11px; font-weight: bold; padding: 4px 12px; border-radius: 20px; margin-bottom: 20px; letter-spacing: 0.08em; text-transform: uppercase; }
    .body { padding: 28px 32px; }
    .field { margin-bottom: 16px; }
    .label { font-size: 11px; color: #6b7280; font-weight: 700; text-transform: uppercase; letter-spacing: 0.1em; margin-bottom: 4px; }
    .value { font-size: 15px; color: #1f2937; font-weight: 600; word-break: break-word; }
    .message-box { background: #f8fafc; border-left: 4px solid #00b4d8; border-radius: 6px; padding: 14px 16px; font-size: 14px; color: #374151; line-height: 1.6; margin-top: 4px; }
    .divider { border: none; border-top: 1px solid #e5e7eb; margin: 20px 0; }
    .footer { background: #f8fafc; padding: 16px 32px; text-align: center; font-size: 12px; color: #9ca3af; }
    .footer a { color: #00b4d8; text-decoration: none; }
  </style>
</head>
<body>
  <div class="wrapper">
    <div class="header">
      <h1>New Contact Inquiry</h1>
      <p>Shark Bond — Chemseal Industries Website</p>
    </div>
    <div class="body">
      <span class="badge">Contact / Product Inquiry</span>

      <div class="field">
        <div class="label">👤 Full Name</div>
        <div class="value">${name.trim()}</div>
      </div>
      <div class="field">
        <div class="label">📱 Mobile Number</div>
        <div class="value"><a href="tel:${mobile.trim()}" style="color:#00b4d8">${mobile.trim()}</a></div>
      </div>
      <div class="field">
        <div class="label">✉️ Email Address</div>
        <div class="value"><a href="mailto:${email.trim()}" style="color:#00b4d8">${email.trim()}</a></div>
      </div>
      ${company_name ? `
      <div class="field">
        <div class="label">🏢 Company / Business</div>
        <div class="value">${company_name.trim()}</div>
      </div>` : ''}
      ${product_id ? `
      <div class="field">
        <div class="label">📦 Product of Interest</div>
        <div class="value">${product_id}</div>
      </div>` : ''}

      <hr class="divider" />

      <div class="field">
        <div class="label">💬 Message</div>
        <div class="message-box">${message.trim().replace(/\n/g, '<br/>')}</div>
      </div>

      <hr class="divider" />

      <div class="field">
        <div class="label">🕒 Received At</div>
        <div class="value" style="font-size:13px;color:#6b7280;">${receivedAt} (IST)</div>
      </div>
    </div>
    <div class="footer">
      This email was automatically generated by the Shark Bond website contact form.<br/>
      <a href="https://wa.me/918866604466">Reply via WhatsApp</a> &nbsp;|&nbsp;
      <a href="mailto:${email.trim()}">Reply to ${name.trim()}</a>
    </div>
  </div>
</body>
</html>`;

    await transporter.sendMail({
      from: MAIL_FROM,
      to: MAIL_TO,
      replyTo: email.trim(),
      subject: `📩 New Contact Inquiry — ${name.trim()}${company_name ? ` (${company_name.trim()})` : ''}`,
      html: htmlBody,
    });

    return NextResponse.json({ success: true, message: 'Inquiry submitted successfully' });

  } catch (error) {
    console.error('Contact inquiry error:', error);
    return NextResponse.json(
      { error: 'Failed to process inquiry. Please try again later.' },
      { status: 500 }
    );
  }
}
